apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  namespace: production
  labels:
    app: landing-page
spec:
  selector:
    matchLabels:
      app: landing-page
  replicas: 1
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: landing-page
        image: prihuda22/landingpage-sp3:v1
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: landing-page
  namespace: production
spec:
  selector:
    app: landing-page
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer