apiVersion: v1
kind: ConfigMap
metadata:
  name: fb-configmap-sp3
  namespace: staging
data:
  config.php: |
    <?php
    $db_host = "bp-1.cempee1flq9r.ap-southeast-1.rds.amazonaws.com";
    $db_user = "rafiadmin";
    $db_pass = "root1234";
    $db_name = "dbsosmed_prod";
    try {    
      //create PDO connection
      $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
      //show error
      die("Terjadi masalah: " . $e->getMessage());
    }
    ?>