apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook
  namespace: staging
  labels:
    app: facebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebook
  template:
    metadata:
      labels:
        app: facebook
    spec:
      volumes:
        - name: config-fb
          configMap:
            name: fb-configmap-sp3
      containers:
      - name: sosial-media
        image: prihuda22/sosial-media-sp3:v2
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-fb
          mountPath: "/var/www/html/config.php"
          subPath: "config.php"
---
kind: Service
apiVersion: v1
metadata:
  name: facebook
  namespace: staging
spec:
  selector:
    app: facebook
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: LoadBalancer
